### ISSUE TITLE
Path not working.

### ISSUE THREAD

**Issue by philipbaginski** [oneduo/nova-file-manager#105]
Hi!

With last Nova 4.19 path is not working. 

```
 FileManager::make(__('Photos'), 'photos')->path('/photos'),
```

**Comment by Rezrazi** [comment]
Hi
The `path()` method does not exist on the File Manager, please double check your code

**Comment by philipbaginski** [comment]
> Hi The `path()` method does not exist on the File Manager, please double check your code

Okay. Is there any way to point into specific folder?

**Comment by mikaelpopowicz** [comment]
You may use the `filesystem` method to choose a configured disk or to create an on-demand filesystem, see [on-demand filesystem](https://oneduo.github.io/nova-file-manager/access-control.html#on-demand-filesystem) documentation section.
