### ISSUE TITLE
Minifying / conversions of uploaded images

### ISSUE THREAD

**Issue by Elvinca** [oneduo/nova-file-manager#107]
Hi there, 

Is there a way now (or is it planned to be feature of this plugin) to convert media automatically on upload to .webp / .avif, or maybe to minify images or to create conversions (small / medium thumbnails etc...)

Thanks in advance :)

**Comment by Rezrazi** [comment]
Hi

For now, we don't ship a native ability to handle this use case. We might consider it in a future release and we'd also be happy to look into a PR for the matter.

You may want to use the `FileUploaded` event documented here https://oneduo.github.io/nova-file-manager/events.html and apply your modifications and conversions to the file. 
We will be adding more to the event's properties in a release coming soon to provide more data to the events, but you can just use the events already if you wish.

Cheers,
Charaf
