### ISSUE TITLE
Hook before renaming files and folders

### ISSUE THREAD

**Issue by Elvinca** [oneduo/nova-file-manager#108]
Hello,

I am facing a problem. When user renames a file / folder, I need all paths associated with this file / folder to get changed. Is there any hook or something that could help me resolve this? 

Many thanks in advance. :)

**Comment by Rezrazi** [comment]
Hi
Can you clarify a bit more what you mean by "_all paths associated with this file / folder to get changed_" ?

**Comment by Elvinca** [comment]
For example, I have resource with image saved as "{'disk':'public','path':'foo/bar/image.jpg'}" and I will rename the file to "image_renamed.jpg" in file manager. After renaming I need the path in resource's image column to get changed to  
"{'disk':'public','path':'foo/bar/image_renamed.jpg'}". This would apply for all resources which have this image set in their fields...

Let me know if you need any more clarification.

Thanks.

**Comment by mikaelpopowicz** [comment]
Hi @Elvinca

You may listen to the `FileRenamed` event. You will find the event documentation [here](https://oneduo.github.io/nova-file-manager/events.html).

Regards
