### ISSUE TITLE
Use Filemanager in Nova TinyMCE images upload

### ISSUE THREAD

**Issue by Elvinca** [oneduo/nova-file-manager#110]
Hello there, is there a way to use this filemanager with nova TinyMCE ? I tried to put this inside nova-tinymce.php config file but I am getting 404 error.

`
'use_lfm' => true,
'lfm_url' => 'nova/nova-filemanager',
`

thanks in advance. :)

**Comment by Elvinca** [comment]
Okay I resolved 404 error because of missing "-" in lfm_url.

`
'use_lfm' => true,
'lfm_url' => 'nova/nova-file-manager'
`

But I only get filemanager iframe:

![image](https://user-images.githubusercontent.com/70513191/204293371-3d777291-0af2-4202-9ec6-c4d2b51dbae5.png)

So I think it looks like I can only copy the URL of image and paste it in

![image](https://user-images.githubusercontent.com/70513191/204293640-1e6fe203-786d-4e39-81db-03001286946b.png)

Or is there a way to upload somehow image into tiny editor directly?

**Comment by Rezrazi** [comment]
Hi @Elvinca 

Unfortunately, we do not ship native support for TinyMCE, but we would happily consider a PR for the matter to make the integration easier for those who need it.

We plan to release a new editor for Nova which will have streamlined integration with our file manager package. No ETA for the time being but it's coming soon.

Cheers,
Charaf

Related to https://github.com/oneduo/nova-file-manager/issues/92#issuecomment-1289318856
