### ISSUE TITLE
404 error on File Manager tool

### ISSUE THREAD

**Issue by piotrh052b** [oneduo/nova-file-manager#112]
**Describe the bug**
The tool window does not appear due to error 404

**To Reproduce**

1. Inastall package
2. Register the tool in your NovaServiceProvider.php file
3. Click entry File Manager in navigation

**Expected behavior**
Tool window should appear

**Screenshots**
<img width="836" alt="image" src="https://user-images.githubusercontent.com/64467371/208292203-e6e1f61a-fe99-4406-a05d-2672daa72e7e.png">

PHP v8.0.8
Laravel Nova v 4.19.5

**Comment by Rezrazi** [comment]
I'm unable to reproduce, please check your app configuration and that you are running the latest version of the package. 
Otherwise, can you please create a reproduction repo ?

**Comment by piotrh052b** [comment]
The error seems to only occur on Windows machine.
I installed this package on production server with linux and there everything works as expected.
Are you able to check this error on Windows ? I'm using Laragon for development purposes.

**Comment by Rezrazi** [comment]
Using the package should not be dependent on which platform you're on. 
Sadly I'm unable to test on a Windows machine. 
I would strongly recommend you double check your environment setup and your hosts with Laragon.

**Comment by piotrh052b** [comment]
I think I found the source of the problem.

In web.php i have route:
`Route::get('/{slug?}', [PageController::class, 'show'])
    ->where('slug', '.+')
    ->name('page__show');`

If I remove this code then the tool works as it should. 

Greetings and thanks for your support.

**Comment by Rezrazi** [comment]
Glad you were able to resolve it. Cheers

**Comment by InfoSimoneGiusti** [comment]
Hello guys, i had the same problem and i has found the solution.

In ToolServiceProvider.php of this plugins, you should move:

`$this->routes();` call from boot() method to register() method.

If during next days i have some free times, i will send a PR with fix.

**Comment by hayatbiralem** [comment]
> Hello guys, i had the same problem and i has found the solution.
> 
> In ToolServiceProvider.php of this plugins, you should move:
> 
> `$this->routes();` call from boot() method to register() method.
> 
> If during next days i have some free times, i will send a PR with fix.

Thank you, this worked. Can we have a workaround in app for this until PR came out? Because production deploys will remove manual updates.

**Comment by hayatbiralem** [comment]
I've extended the package's ToolServiceProvider.php in my app and add call routes in register method as follows:

```php
<?php

// app/Providers/CustomFileManagerServiceProvider.php

namespace App\Providers;

use Oneduo\NovaFileManager\ToolServiceProvider as NovaFileManagerServiceProvider;

class CustomFileManagerServiceProvider extends NovaFileManagerServiceProvider
{
    public function register(): void
    {
        parent::register();

        $this->routes();
    }
}
```

... and registered it in app config as follows:

```php
<?php

// config/app.php

// ...

return [

    'providers' => [

       // ...

        /*
         * Package Service Providers...
         */
        App\Providers\CustomFileManagerServiceProvider::class,

       // ...

    ],

    // ...
];
```

It appears to be working. This solution will suffice until a proper fix is implemented, in my opinion.
