### ISSUE TITLE
Select multiple files

### ISSUE THREAD

**Issue by tovantiep** [oneduo/nova-file-manager#114]
Select multiple photos but no action, I want selected photos to be deleted or put in another folder, do you have any solution?
![image](https://user-images.githubusercontent.com/74131799/208807496-59ed7a86-4b04-4c96-8ee6-eecf6f009930.png)
Currently I only see a clear selected button !

**Comment by Rezrazi** [comment]
Sorry for the delay to answer your question. We were away for a while.
Currently there is no option to apply bulk actions to files (delete, move...)
We plan to add it in a future release coming soon. Please check back again soon.

**Comment by Rezrazi** [comment]
bulk delete was added in https://github.com/oneduo/nova-file-manager/pull/103
bulk move is not yet supported and planned for the time being
Thanks
