### ISSUE TITLE
Translation is not working

### ISSUE THREAD

**Issue by DuyenNguyen66** [oneduo/nova-file-manager#115]
**Describe the bug**
Error messages in `errors.php`,` messages.php` and `validation.php` not change by locale. But `ui.php` works.

**To Reproduce**

1. Create 3 files above, change message in another language.
2. F5 the page
3. Input wrong data
4. Submit form, and nothing gonna change.

**Screenshots**
![image](https://user-images.githubusercontent.com/37392541/208881349-af9dffd8-d05c-4cc5-bf25-d647001267fe.png)

**Comment by Rezrazi** [comment]
Can you please give more details about which files you have created and where they're placed in your file tree ?
Thanks

**Comment by DuyenNguyen66** [comment]
Thank for responding. Here is my file tree.
![image](https://user-images.githubusercontent.com/37392541/210484744-583dc51d-9b7a-42f0-83a9-b7a32401ef03.png)

And I've viewed ` src/ToolServiceProvider.php`, `boot()` method and seen the code below:
![image](https://user-images.githubusercontent.com/37392541/210485376-e4a7f74b-0b26-4ca8-8d5b-44a829d0a31b.png)

Maybe you forgot to call another files (`errors.php`, `messages.php` and `validation.php`) in `trans()`

**Comment by Rezrazi** [comment]
Hi, sorry for taking long to get back to you on this, been quite busy lately.

Unfortunately I'm unable to reproduce this.

To get translations working, you need to put your translations under the following path `<root>/lang/vendor/nova-file-manager/<locale>`

e.g. `lang/vendor/nova-file-manager/fr/` you would need to copy the files needed 
```
errors.php
messages.php
ui.php
validation.php
```
and edit them to your liking

Please make sure you do not have a `resources/lang` folder present, as it might introduce unexpected behaviors to have both, one should move translations to the `lang` folder

If you still encountering issues regarding this, please provide some more details or perhaps a demo repo which would help replicate this.

Cheers
