### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by philipbaginski** [oneduo/nova-file-manager#116]
Hi everyone!

I don't know if this is a bug or I do something wrong, but navigating through FileManager I can see in breadcrumbs only Home - as icon - and latest folder I reached. There is no way to make step back, and breadcrumbs does not give this option as well. E.g. I Have in main public folder 5 subfolders and in some of them I have sub sub folders. If I will navigate into sub sub folder, there is no button to go back to sub folder, and breadcrumbs gives the only option to go Home - public folder.

**Comment by Rezrazi** [comment]
Hi

To further investigate this, could you provide a screencast of the behavior ?

Thanks
