### ISSUE TITLE
Cannot delete files within folder when the foder starts with a `whitespace`

### ISSUE THREAD

**Issue by milewski** [oneduo/nova-file-manager#119]
**Describe the bug**

Today I faced a weird issue where files could not be deleted/renamed/moved (everything else worked) when the folder they were placed started with a `whitespace` 

**To Reproduce**

1. Create a folder that begins with a whitespace ` ExampleFolder`
2. Upload an image to it...
3. Try to delete the image...
4. See the error 

<img width="510" alt="18a9c9b4de098b51315aabc427853cd" src="https://user-images.githubusercontent.com/2874967/211476047-6b35d095-fd4d-4783-94be-94ee1a09da40.png">

**Expected behavior**

Folder name should be trimmed when created or the filesystem should not crash if it contains it...

**Comment by Rezrazi** [comment]
Hi @milewski 

Thanks for the report. This should be fixed in the next minor release.

This is just a mitigation as in the next 0.8 typescript release the store is being partially rewritten and would better handle input sanitization.

Cheers
