### ISSUE TITLE
Object of class BBSLab\NovaFileManager\Support\Asset could not be converted to string

### ISSUE THREAD

**Issue by eno7x** [oneduo/nova-file-manager#121]
Hello, I am getting this error. 
"Object of class BBSLab\NovaFileManager\Support\Asset could not be converted to string"

**Comment by Rezrazi** [comment]
Hi

Without full context I can't really determine what's causing this, and I'm unable to provide much help.
My first guess would be that you're missing the required model casts as described here https://oneduo.github.io/nova-file-manager/installation.html#casting-your-model-attributes

**Comment by mikaelpopowicz** [comment]
https://github.com/oneduo/nova-file-manager/pull/123 seems to resolve it.
