### ISSUE TITLE
Cannot select image from preview modal

### ISSUE THREAD

**Issue by miagg** [oneduo/nova-file-manager#132]
If you double-click on an image for a quick preview you cannot "quickly" select it and return back to the resource. You have to close the modal and then select the image.

![screenshot](https://user-images.githubusercontent.com/6439071/214547736-fb34158e-35c7-4e68-934d-fecc2953fe37.png)

**To Reproduce**

## Scenario 1
1. On a FileManager field click on "Choose Image"
2. On the tool double-click a random image to open the preview modal.
3. There is no "select" action to use the image in the field.

## Scenario 2
1. On a FileManager field click on "Choose Image"
2. On the tool click on the search button and search for an existing image.
3. The preview modal appears but with no "select" action to use the image.

**Expected behavior**
A "select" action should be added to the list of actions on top, preferably as last action.

**Screenshots**
Posted above

**Desktop (please complete the following information):**

- OS: MacOS Monterey 13.1
- Browser Chrome
- Version 109

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Not Applicable

**Comment by Rezrazi** [comment]
added in https://github.com/oneduo/nova-file-manager/pull/103
Thanks
