### ISSUE TITLE
Is search intended to work only in currently opened folder ?

### ISSUE THREAD

**Issue by Elvinca** [oneduo/nova-file-manager#145]
Hi there, I would like to ask if the search functionallity is intended to work only in currently active (opened) directory? Shouldn't it work multilevel like across whole filesystem ? Because if I try to search some file which is nested two or three levels, it wont find it.

Thanks

**Comment by mikaelpopowicz** [comment]
Hi @Elvinca 

For the time being, the search is scoped on the current folder.
