### ISSUE TITLE
Chunks do not get deleted after successful upload

### ISSUE THREAD

**Issue by miagg** [oneduo/nova-file-manager#158]
I noticed the `chunks` folder inside the storage has grown in size. I realized that every single image uploaded to the system has a `.part` file stored in this folder. I guess this was meant to be a temporary folder that is used to upload images and then move them to the correct folder. But instead the images stay there.

**To Reproduce**
1. Upload one or more images
2. Check on `storage/chunks`

**Expected behavior**
The folder should be empty

**Screenshots**
<img width="687" alt="Screenshot 2023-02-07 at 11 03 36 AM" src="https://user-images.githubusercontent.com/6439071/217200873-1d48cc58-b11c-4874-801c-96d590b33125.png">

**Desktop (please complete the following information):**

- OS: Mac OS Monterey 13.2
- Browser Chrome
- Version 109

**Comment by mikaelpopowicz** [comment]
Hi @miagg 

The upload feature relies on [laravel chunk upload package](https://github.com/pionl/laravel-chunk-upload), you may take a look at the [configuration file](https://github.com/pionl/laravel-chunk-upload/blob/master/config/chunk-upload.php).

You may enable [task scheduling](https://laravel.com/docs/9.x/scheduling#running-the-scheduler) (cron) to run the `uploads:clear` command.
