### ISSUE TITLE
Choose a photo when updating

### ISSUE THREAD

**Issue by tovantiep** [oneduo/nova-file-manager#160]
I do photo editing, when I search by image name and click on it. The results show 2 photos including old and new photos like videos.

https://user-images.githubusercontent.com/74131799/217764794-3463e248-ea06-4a85-9350-45ad6cca455c.MP4

**Comment by mikaelpopowicz** [comment]
Hi @tovantiep 

Indeed, image editing allows you to upload a new version of the original image without overwriting it.
