### ISSUE TITLE
Filemanager field doesn't works with translatable fields

### ISSUE THREAD

**Issue by ExsyDev** [oneduo/nova-file-manager#168]
Hello. When I use translatable field by spatie/nova-translatable, filemanager doesn't work, I get error: Call to a member function map() on string, when I go to resource

**Comment by Rezrazi** [comment]
Hi @ExsyDev 

Could you provide a simple example to reproduce this ? And have you tried wrapping your field https://oneduo.github.io/nova-file-manager/field.html#third-party-compatibility

**Comment by TEstDevelo** [comment]
He have trait on Model HasTranslations, from spatie/laravel-translatable, and package https://github.com/spatie/nova-translatable. He writed in resource:

        Translatable::make([
                FileManager::make('Image', 'file'),

And he get error: Call to a member function map() on string, If you use without this field (Translatable::make()), then package FileManager works fine.

**Comment by aglonietis** [comment]
@ExsyDev You must cast the attribute to 'object' or 'array'.

    protected $casts = [
        'file' => 'object'
    ];
