### ISSUE TITLE
Undefined property: Oneduo\NovaFileManager\NovaFileManager::$attribute

### ISSUE THREAD

**Issue by HeadStudios** [oneduo/nova-file-manager#176]
**Describe the bug**
The following error stack trace when tryign to render my laravel Nova resource:
[2023-02-21 11:14:50] local.ERROR: Undefined property: Oneduo\NovaFileManager\NovaFileManager::$attribute {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined property: Oneduo\\NovaFileManager\\NovaFileManager::$attribute at /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/Fields/FieldCollection.php:137)
[stacktrace]

**To Reproduce**
composer require then config setup command - 

Video for context:
https://share.getcloudapp.com/L1uDnE82

**Expected behavior**
Nova File Manager to display

**Screenshots**
Video for context: https://share.getcloudapp.com/L1uDnE82

**Desktop (please complete the following information):**

- OS: MacOS
- Chrome
- Version 110.0.5481.100 (Official Build) (arm64)

**Additional context**
Followed instructions and got error - my Campaign Nova resource:
https://gist.github.com/HeadStudios/8e9598b9266f898e65efbce082810695

**Comment by Rezrazi** [comment]
Hi @HeadStudios 
Thank you for your report, however, are you sure you're using the field and not the tool on your resource ?
Please check that you're importing `Oneduo\NovaFileManager\FileManager`

```php
// app/Nova/Project.php

use Oneduo\NovaFileManager\FileManager;

class Project extends Resource
{
    // ...

    public function fields(NovaRequest $request): array
    {
        return [
            // ... any other fields
            FileManager::make(__('Attachments'), 'attachments'),
        ];
    }
}
````
https://oneduo.github.io/nova-file-manager/field.html#basic-usage

**Comment by HeadStudios** [comment]
> Hi @HeadStudios Thank you for your report, however, are you sure you're using the field and not the tool on your resource ? Please check that you're importing `Oneduo\NovaFileManager\FileManager`
> 
> ```
> // app/Nova/Project.php
> 
> use Oneduo\NovaFileManager\FileManager;
> 
> class Project extends Resource
> {
>     // ...
> 
>     public function fields(NovaRequest $request): array
>     {
>         return [
>             // ... any other fields
>             FileManager::make(__('Attachments'), 'attachments'),
>         ];
>     }
> }
> ```
> 
> https://oneduo.github.io/nova-file-manager/field.html#basic-usage

Thank you so much! You're right this has fixed my problem - however I am still unable to see files due to the following error: I am getting 403 Not Found after attempting to open the File Explorer.

Any input on any potential causes as no error is shown in laravel.log 
https://share.getcloudapp.com/geuEj9r9

Thanks!

**Comment by mikaelpopowicz** [comment]
Hi @HeadStudios 

Please may you provide the api response from the developper tools ?

**Comment by HeadStudios** [comment]
> Hi @HeadStudios
> 
> Please may you provide the api response from the developper tools ?

Can you please elaborate on what you mean by api response from developer tools? Where would I find this information? Thanks!

**Comment by mikaelpopowicz** [comment]
The browser developper tools, you can open it by right clicking the web page > Inspect. Open the `Network` tab,  you will see all http requests sent by your browser. We are looking for a request with a path similar as `/nova-vendor/nova-file-manager/campaigns`. Click on the request an copy the value of the request's `Preview` tab.

**Comment by HeadStudios** [comment]
> The browser developper tools, you can open it by right clicking the web page > Inspect. Open the `Network` tab, you will see all http requests sent by your browser. We are looking for a request with a path similar as `/nova-vendor/nova-file-manager/campaigns`. Click on the request an copy the value of the request's `Preview` tab.

Hi, thank you for clarifying. I've just checked and you can see information below:
Request URL: https://rrdevours.monster/nova-vendor/nova-file-manager/disks/campaigns
Request Method: GET
Status Code: 403 
Remote Address: 137.184.57.235:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-origin: *
cache-control: no-cache, private
content-encoding: gzip
content-type: text/html; charset=UTF-8
date: Tue, 21 Feb 2023 23:55:33 GMT
server: nginx
set-cookie: XSRF-TOKEN=eyJpdiI6IjJ1WE90cStjNWZETE9raDErT0JJS3c9PSIsInZhbHVlIjoiUC9rVlJCNlFXdzhXU0V3YXk0cmRSWkxJZVNZOEkxQWgxbkQzUldIL3Rxdm8yK3MrWXMwL2F4SXZud3V6SzRqUTBpZGNLYllycVMzNy9TbjZ4eExuY3l4MXNldUh5c0N3RmVhMkRXUkRSbnVPNlprTEVQZDU5SCtWKzhDUEt0a2YiLCJtYWMiOiJmYTI0OGY0NDZhOWVkYTNjZmMyODA0YTRlZGZlOTQ4YmNjNTMzY2JjMDQzMDEwOGQyMjUxMTEyNTAzZjhkZmU4IiwidGFnIjoiIn0%3D; expires=Wed, 22 Feb 2023 01:55:33 GMT; Max-Age=7200; path=/; samesite=lax
set-cookie: laravel_session=eyJpdiI6InI3QlU3aFpTTmtRN3JoMGJXS1FZL1E9PSIsInZhbHVlIjoiNjlocUdhUU5Qa2VzRHk5TEJPcGhBMmY4cFNML0dKUkJ5aVcrS3J6MWE0cEJNQmpSYnh6TndZQ2Z1WWh4eVRmcjM3RThqRzhZbkxtNlJMNjcrakRQdG1qM2dCL0JDY3FyYnMwOTFZZzlGVXRpVFpLcVBjWkN4T2R2dDl5NFhZWjciLCJtYWMiOiIwMGEyNTlhYWNlZjI2MDc0MTY1Mzk0YTAyOWNlZDQ1MWUyMzdjZTlkOTE0NzEwNmU0Nzg3M2YzNDdjNDFhZDJlIiwidGFnIjoiIn0%3D; expires=Wed, 22 Feb 2023 01:55:33 GMT; Max-Age=7200; path=/; httponly; samesite=lax
vary: Accept-Encoding
vary: X-Inertia
:authority: rrdevours.monster
:method: GET
:path: /nova-vendor/nova-file-manager/disks/campaigns
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cookie: amp_adc4c4=EDMCpOcLRbWGx6tfk4Z7vm...1gf7uusff.1gf7uusff.0.0.0; amp_d915a9=rRnOFtfgW_2iLedx_F2zHt...1gf7uuup0.1gf7uuup0.0.0.0; XDEBUG_SESSION=XDEBUG_ECLIPSE; _ga_PYR7Y09GFB=GS1.1.1666505765.1.1.1666505844.0.0.0; _ga=GA1.1.2054414514.1661593840; _ga_80TZF30Q47=GS1.1.1677021986.467.1.1677022406.0.0.0; XSRF-TOKEN=eyJpdiI6IjlGVjBDNVEzZGM2Um5xdHZMV0Y0V1E9PSIsInZhbHVlIjoiMjF1RWo3c1ZCZ004TjhGVlgrZDRjTUlsaUxOS3JMWEhERE55VGJhc2ZhcHFtVG9IZ0JxUlo4eXJYZm5ncEI0YVFJdUMrd1FQK3JMbTBRd093dERTbWRqTTVrUlY3dkE5YzExNng3TGNHL29wNzJrNlRJQU9xNEVRdURKM3pzSWEiLCJtYWMiOiJkNTFjYTMyMDQyM2I4NmJhMjc0ZTJkM2RhMGVjNTc3NzYxN2IxZmZlNDRhMTJkNzQyZDg2NTgxZWI0Y2EyZTRiIiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6Ii9KUFh6WGdERFJKTXpvdWVUOXdHRHc9PSIsInZhbHVlIjoiM3RXZFBWamgraTBOTkhEQUdJcUZMWXg4Q0ZWUlZTUzFNSzN0dlpJOEJicGtsTFp2UUhqd01nQ0M0OVc0ZmtRSVVaV0tUQ2xnVG5MSjhkc2Y4NmNCMjRjbHNRVUdRZU95MDVJdDJMTTllT2Z3Z1kwU20yVElsZlEvc3A1RUQ1MlciLCJtYWMiOiI0MWVmOWMzZmY5NzRlOGUzNTM5YWY4MGRmMzI0NDU3MTBhMjU5NjU4NTBmNDAxMDFiMTU5M2ExODEwZjE4YzcyIiwidGFnIjoiIn0%3D
referer: https://rrdevours.monster/nova/resources/campaigns/322/edit
sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
x-csrf-token: 7CYJygPEKUP8iQ1cFG9caxeqNqvIcEbhiFUxtUvV
x-requested-with: XMLHttpRequest
x-xsrf-token: eyJpdiI6IjlGVjBDNVEzZGM2Um5xdHZMV0Y0V1E9PSIsInZhbHVlIjoiMjF1RWo3c1ZCZ004TjhGVlgrZDRjTUlsaUxOS3JMWEhERE55VGJhc2ZhcHFtVG9IZ0JxUlo4eXJYZm5ncEI0YVFJdUMrd1FQK3JMbTBRd093dERTbWRqTTVrUlY3dkE5YzExNng3TGNHL29wNzJrNlRJQU9xNEVRdURKM3pzSWEiLCJtYWMiOiJkNTFjYTMyMDQyM2I4NmJhMjc0ZTJkM2RhMGVjNTc3NzYxN2IxZmZlNDRhMTJkNzQyZDg2NTgxZWI0Y2EyZTRiIiwidGFnIjoiIn0=

Request URL: https://rrdevours.monster/nova-vendor/nova-file-manager/campaigns?path=%2F&perPage=15&attribute=nova_file&resource=campaigns&fieldMode=true&resourceId=322
Request Method: GET
Status Code: 403 
Remote Address: 137.184.57.235:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-origin: *
cache-control: no-cache, private
content-encoding: gzip
content-type: text/html; charset=UTF-8
date: Tue, 21 Feb 2023 23:55:33 GMT
server: nginx
set-cookie: XSRF-TOKEN=eyJpdiI6Ilczc3A5T2lMdlZGQ1FYMU1NeHhBN0E9PSIsInZhbHVlIjoiTnp6VEVKQnIyd0IzZTRNNDc1MEhaNDNva1RSNXU1d2RZZ3VlcHB1cTFLc3F3TWJBbUtYWXpsL1lnYXlHM2ttbE11Q0JXVmpRRVhMTlo2U2E3NXRaWkhiNG9ReVVCZHdqUFFhNzhRMnFjRU1SY0R6SlFXcjV6clhJMGxNUGtjb3giLCJtYWMiOiIwYmY4YzI3NDMwNmQ1MWZiODRlOTZmMTQ0ZDZlMjQ2YWQzYjY5ZmUxY2E4NjM4NDc1NDdhOWRjMGE3MjYzN2Y0IiwidGFnIjoiIn0%3D; expires=Wed, 22 Feb 2023 01:55:33 GMT; Max-Age=7200; path=/; samesite=lax
set-cookie: laravel_session=eyJpdiI6Ik5EVENpeTM4ay9ieFRxRkVlTTkrRkE9PSIsInZhbHVlIjoiTWUwVlI4OXNobmxnRWhVYWl6SytpQ0tCS1NIZm1JQnh0ZFNGQ1I2K2dyNjg3aDcxR24rMWN2R3lqWGtHbzIvS3ZROEhFd1J0RjJmRk40ZnVRWEFjWFlqNGpNT1AzcG1WUmVYcVMzQ29HZEhWZFluWk9vbDhxbzg2R2xiL1p4YjAiLCJtYWMiOiI2NDc4ZmI0YzcyMDMyYjhmYmJhNmVhNjYwOTZhZmFhYjExOTRkMzEzMzQwMTkyZDFiMGMwYzFhNWUyZWY2ODEwIiwidGFnIjoiIn0%3D; expires=Wed, 22 Feb 2023 01:55:33 GMT; Max-Age=7200; path=/; httponly; samesite=lax
vary: Accept-Encoding
vary: X-Inertia
:authority: rrdevours.monster
:method: GET
:path: /nova-vendor/nova-file-manager/campaigns?path=%2F&perPage=15&attribute=nova_file&resource=campaigns&fieldMode=true&resourceId=322
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cookie: amp_adc4c4=EDMCpOcLRbWGx6tfk4Z7vm...1gf7uusff.1gf7uusff.0.0.0; amp_d915a9=rRnOFtfgW_2iLedx_F2zHt...1gf7uuup0.1gf7uuup0.0.0.0; XDEBUG_SESSION=XDEBUG_ECLIPSE; _ga_PYR7Y09GFB=GS1.1.1666505765.1.1.1666505844.0.0.0; _ga=GA1.1.2054414514.1661593840; _ga_80TZF30Q47=GS1.1.1677021986.467.1.1677022406.0.0.0; XSRF-TOKEN=eyJpdiI6IjlGVjBDNVEzZGM2Um5xdHZMV0Y0V1E9PSIsInZhbHVlIjoiMjF1RWo3c1ZCZ004TjhGVlgrZDRjTUlsaUxOS3JMWEhERE55VGJhc2ZhcHFtVG9IZ0JxUlo4eXJYZm5ncEI0YVFJdUMrd1FQK3JMbTBRd093dERTbWRqTTVrUlY3dkE5YzExNng3TGNHL29wNzJrNlRJQU9xNEVRdURKM3pzSWEiLCJtYWMiOiJkNTFjYTMyMDQyM2I4NmJhMjc0ZTJkM2RhMGVjNTc3NzYxN2IxZmZlNDRhMTJkNzQyZDg2NTgxZWI0Y2EyZTRiIiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6Ii9KUFh6WGdERFJKTXpvdWVUOXdHRHc9PSIsInZhbHVlIjoiM3RXZFBWamgraTBOTkhEQUdJcUZMWXg4Q0ZWUlZTUzFNSzN0dlpJOEJicGtsTFp2UUhqd01nQ0M0OVc0ZmtRSVVaV0tUQ2xnVG5MSjhkc2Y4NmNCMjRjbHNRVUdRZU95MDVJdDJMTTllT2Z3Z1kwU20yVElsZlEvc3A1RUQ1MlciLCJtYWMiOiI0MWVmOWMzZmY5NzRlOGUzNTM5YWY4MGRmMzI0NDU3MTBhMjU5NjU4NTBmNDAxMDFiMTU5M2ExODEwZjE4YzcyIiwidGFnIjoiIn0%3D
referer: https://rrdevours.monster/nova/resources/campaigns/322/edit
sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
x-csrf-token: 7CYJygPEKUP8iQ1cFG9caxeqNqvIcEbhiFUxtUvV
x-requested-with: XMLHttpRequest
x-xsrf-token: eyJpdiI6IjlGVjBDNVEzZGM2Um5xdHZMV0Y0V1E9PSIsInZhbHVlIjoiMjF1RWo3c1ZCZ004TjhGVlgrZDRjTUlsaUxOS3JMWEhERE55VGJhc2ZhcHFtVG9IZ0JxUlo4eXJYZm5ncEI0YVFJdUMrd1FQK3JMbTBRd093dERTbWRqTTVrUlY3dkE5YzExNng3TGNHL29wNzJrNlRJQU9xNEVRdURKM3pzSWEiLCJtYWMiOiJkNTFjYTMyMDQyM2I4NmJhMjc0ZTJkM2RhMGVjNTc3NzYxN2IxZmZlNDRhMTJkNzQyZDg2NTgxZWI0Y2EyZTRiIiwidGFnIjoiIn0=

Does this help?

Video below for context:
https://p147.p4.n0.cdn.getcloudapp.com/items/Kou90l5v/8105b937-a1ef-42c3-957d-09dbcb690e5b.mp4?v=8b429322d0896870991f24ed8388307b

**Comment by Rezrazi** [comment]
@HeadStudios thank you for this, but we're more interested in the actual "response", please take a moment to check out how to take the response out of the devtools from your browser, as it will be of great help for us to be able to understand your issue and investigate it if necessary 

Cheers

**Comment by HeadStudios** [comment]
Hi,

Below is response to
https://rrdevours.monster/nova-vendor/nova-file-manager/campaigns?path=%2F&perPage=15&attribute=nova_file&resource=campaigns&fieldMode=true&resourceId=318

Looks like I'm getting a 403 response:
https://share.getcloudapp.com/nOuKE205

Hope this is to your satifaction - let me know if more digging is required from me.

**Comment by Rezrazi** [comment]
Hi @HeadStudios 

Thank you for getting back to us, but we're more interested in the preview tab here 
![CleanShot 2023-02-28 at 09 57 48](https://user-images.githubusercontent.com/2086576/221803383-26d85008-5364-455f-a6d9-973fe583f596.png)

Try to restart from the beginning, and provide us with the response for your 403 error (be sure to go Preview and then copy the whole object by right clicking)

And for the sake of keeping clutter from the issue as this JSON may be too long, please use gist.github.com to paste the response

Thanks !

**Comment by HeadStudios** [comment]
Hi,
The preview tab is showing a white screen of death. I am copying 'Response' tabs into gists below:
https://share.getcloudapp.com/8LuqQ9d7

https://gist.github.com/HeadStudios/22f5491dfdaca5f3d95072dc4cfaf16d
https://gist.github.com/HeadStudios/ddb804ca0df594d641bbc9508c21f388

Video for context: https://share.getcloudapp.com/v1uPRjRX

Hope that helps

**Comment by Rezrazi** [comment]
Thanks @HeadStudios 

However at this rate we're not going to be able to get helpful debug data.

Please try to create a minimal repository which replicates your issue, this will enable us to have a clearer vision of your problem and why happens. You may create a new fresh Laravel, install Nova, and create the resource that you have an issue with.

This is really the best course of action to resolve the issue, we thank you for taking the time to actually have screen recordings of your issue, but we would progress better with a repo with a minimal reproduction setup.

Cheers !

**Comment by HeadStudios** [comment]
Hi,

Thank you for your help - I can confirm I have resolved the issue. Thank you for your quick responses!
