### ISSUE TITLE
File Manager very slow on s3 bucket

### ISSUE THREAD

**Issue by HeadStudios** [oneduo/nova-file-manager#221]
**Describe the bug**
Everything works great but seems to be very slow to load folders

**To Reproduce**
Setup Nova File Manager with s3 bucket and navigate/try to upload on Digital Ocean

**Expected behavior**
Reasonably fast

**Screenshots**
Video for context: https://share.getcloudapp.com/Kou91GAR

**Desktop (please complete the following information):**

- MacOS Big Sur
- Chrome
Version 111.0.5563.146 (Official Build) (arm64)

**Comment by HeadStudios** [comment]
I can confirm there are a lot of files in my root S3 folder which will take a while to remove. In the mean time I was wondering if it's possible to set a default folder that opens?

**Comment by HeadStudios** [comment]
Can confirm creating a new system disk and linking to that has fixed the issue. Thank you.

**Comment by onedevquad** [comment]
> Can confirm creating a new system disk and linking to that has fixed the issue. Thank you.

@HeadStudios Can u please explain how you achieve this,i have same slow performance and try to find a solution

**Comment by anusrimix** [comment]
@HeadStudios Can u please explain how you achieve this, I also have same issue.
