### ISSUE TITLE
PDF Viewer doesn't show PDF file or preview?

### ISSUE THREAD

**Issue by Diamundo** [oneduo/nova-file-manager#222]
**Describe the bug**
I've installed the package and uploaded a PDF file. When I open the file manager screen I'm greeted with a gray box where the PDF preview should be. When I click on the file, the file viewer opens with a large gray file viewer but still no PDF file. Only when I click the 'download' icon am I sent to the public file URL and I can see the PDF file through the browser.

**To Reproduce**

0. Install the package through the [installation instructions](https://oneduo.github.io/nova-file-manager/installation.html)
1. Also set up a local storage disk at app/files
2. Upload a PDF file
3. Open the File manager
4. Click on the uploaded file
5. View a nova resource which has the attachment linked

**Expected behavior**
I want to see a preview of the PDF file, or in the file viewer the actual PDF file, instead of a gray / empty block.

**Screenshots**
[See this imgur album](https://imgur.com/a/SptMYpI)

**Desktop**

- OS: MacOS 12.6.1 (21G217)
- Browser: 
  - Chrome 111.0.5563.146 (Official Build) (arm64)
  - Firefox 110.0 (64-bits)
  - Safari 15.6.1 (17613.3.9.1.16)

**Comment by Rezrazi** [comment]
Hi, I just tested with a sample PDF file, and it is working as intended.

Can you provide some more details about your setup (is it an S3 or local storage, the actual PDF file and so on)

![CleanShot 2023-04-12 at 10 05 30](https://user-images.githubusercontent.com/2086576/231393603-df651784-e41d-4227-ac6a-7d690248f4eb.png)

**Comment by Diamundo** [comment]
Hi @Rezrazi, thanks for your reply!

## Config

I'm using the following `filesystem.php` config:
```php
        'files' => [
            'driver' => 'local',
            'root' => storage_path('app/files'),
            'url' => env('APP_URL').'/files',
            'visibility' => 'public',
            'throw' => false,
        ],
```

```php
    'links' => [
        public_path('storage') => storage_path('app/public'),
        public_path('files') => storage_path('app/files'),
    ],
```

and `nova-file-manager.php` config:
```php
    'available_disks' => [
        'public',
        'files',
    ],
```

and env:
```
NOVA_FILE_MANAGER_DISK=files
NOVA_FILE_MANAGER_UPDATE_CHECKER_ENABLED=false
```

I also saw this in the `nova-file-manager` config, perhaps the normal `Entities\File::class` doesn't know how to render/embed the file? As this is the case with all of my testing files that fall under that category.
```php
    'entities' => [
        'image' => \Oneduo\NovaFileManager\Entities\Image::class,
        'video' => \Oneduo\NovaFileManager\Entities\Video::class,
        'default' => \Oneduo\NovaFileManager\Entities\File::class,
    ],
```

## Tests
The files I'm using are also simple PDF's. The one in my screenshots is [chicken.pdf](https://isotropic.org/papers/chicken.pdf), the other file I used was a Google Docs file downloaded as PDF so as simple as it gets.

I've also tested other filetypes by uploading:

- a .png (shows correct), 
- a .zip file (doesn't have a preview but I am able to extract it), 
- a .php and .sh file (code files, no preview whatsoever) 
- and a .pages file (Apple word document, just to see what would happen)

I also have an ad-blocker installed but a) it's showing 0 blocked on the project domain, and b) the other browsers don't use any adblockers and don't work either. Incognito doesn't provide any different results either.  

## Hacking inside the config

If I comment out the 'url' line, I get a 404 instead of a gray block when viewing the file in detail. So that one's clearly required. The visibility line I can comment out without changes. I can also remove the symlink in /public without a 404, though removing the symlink does also break the image preview and image detail. So it seems that one is also necessary. 

## Removing public access to the url's

I've since found [this link](https://laracasts.com/discuss/channels/general-discussion/image-accessibility-for-authenticated-users-only) which explained how to show files behind a login screen. This I like as it prevents unauthorized users from downloading the public file. Ideally there would also be a way to disable the filemanager -> download button, but that's outside the scope of this issue. I've added the following code, however that doesn't show a preview of the file in the file manager window:

```php
// in routes/web.php

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('files/{file}', [\App\Http\Controllers\FileController::class, 'show'])->name('files.show');
});
```

```php
// FileController
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class FileController extends Controller
{    
    public function show(Request $request, string $slug)
    {
        $file = Storage::disk('files')->get($slug);
        return response()->make($file, 200, ['content-type' => '']); //TODO fix
    }    
}
```

and

- Removed the public/files symlink and symlink config
- Kept the files disk config as above

**Comment by Diamundo** [comment]
You're amazing. I was apparently missing the `s` in `https://domain.test` inside the APP_URL environment variable. Once I added the s and checked again, it was working. Thanks!
