### ISSUE TITLE
File Manager Doesn't Work in Laravel Nova Action Fields

### ISSUE THREAD

**Issue by HeadStudios** [oneduo/nova-file-manager#223]
**Describe the bug**
Works fine in a Resource but not in Laravel Nova action field (it just keeps loading)

**To Reproduce**
1. Insert field into Laravel Nova action
2. Try to open it

**Expected behavior**
Should work like in resources

**Screenshots**
Video for context: https://share.getcloudapp.com/JruppQKr

Also following error in Console:
caught (in promise) Error: Request failed with status code 404
    at Ar (nova-file-manager:5:53479)
    at Pr (nova-file-manager:5:53662)
    at XMLHttpRequest.A (nova-file-manager:6:1979)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Chrome (latest version)
- MacOS Big Sur

**Additional context**
Video for context: https://share.getcloudapp.com/JruppQKr

Also following error in Console:
caught (in promise) Error: Request failed with status code 404
    at Ar (nova-file-manager:5:53479)
    at Pr (nova-file-manager:5:53662)
    at XMLHttpRequest.A (nova-file-manager:6:1979)

**Comment by Opetr** [comment]
Third-party compatibility
[#](https://oneduo.github.io/nova-file-manager/field.html#third-party-compatibility)

You may want to use the field inside a custom field or a tool (e.g [Nova Settings](https://github.com/outl1ne/nova-settings) or [Laravel Nova Flexible Content](https://github.com/whitecube/nova-flexible-content)). Some extra configuration is needed to be able to resolve the field during api calls.

**Comment by Opetr** [comment]
> Third-party compatibility [#](https://oneduo.github.io/nova-file-manager/field.html#third-party-compatibility)
> 
> You may want to use the field inside a custom field or a tool (e.g [Nova Settings](https://github.com/outl1ne/nova-settings) or [Laravel Nova Flexible Content](https://github.com/whitecube/nova-flexible-content)). Some extra configuration is needed to be able to resolve the field during api calls.

Add this:

    public function register()
    {
        FileManager::registerWrapper('my_wrapper', function (FileManager $field) {
            // configure the field as you used to
            return $field
                ->multiple()
                // ...
                ->filesystem(fn() => 'public');
        });
    }

**Comment by HeadStudios** [comment]
Thank you so much!
