### ISSUE TITLE
Support storing path without disk in the db

### ISSUE THREAD

**Issue by stevelacey** [oneduo/nova-file-manager#236]
**Is your feature request related to a problem? Please describe.**

Most other storage solutions simply store paths in a text field in the database, so supporting that here makes it easier to migrate from other packages like https://github.com/InfinetyEs/Nova-Filemanager to this one.

**Describe the solution you'd like**

Maybe a setting? Maybe it should even be the default? Storing `{"disk":"public","path":"..."}` is a verbose approach for anyone storing single files using the default storage, and that's probably the most common use case, and supporting this makes onboarding easier for those coming from existing solutions.

**Describe alternatives you've considered**

Extending the cast to handle this is possible, as demonstrated below, but perhaps this should be baked in.

```php
<?php

namespace App\Casts;

use InvalidArgumentException;
use Oneduo\NovaFileManager;
use Oneduo\NovaFileManager\Support\Asset as AssetObject;

class Asset extends NovaFileManager\Casts\Asset
{
    public function get($model, string $key, $value, array $attributes): ?AssetObject
    {
        if ($value === null) {
            return null;
        }

        return new AssetObject(config('nova-file-manager.default_disk'), $value);
    }

    public function set($model, string $key, $value, array $attributes): ?string
    {
        if ($value === null) {
            return null;
        }

        if (is_array($value)) {
            return json_encode($value, JSON_THROW_ON_ERROR);
        }

        if ($value instanceof AssetObject) {
            return $value->path;
        }

        throw new InvalidArgumentException('Invalid value for Asset cast');
    }
}
```

**Comment by Rezrazi** [comment]
Hi

We've made the choice to store the value as a JSON object to enable the multi disk support, in theory, you're able to store multiple values from multiple disks in the same column.

We'll gladly consider a more flexible approach in a PR that gets the best out of the two worlds

Cheers
