### ISSUE TITLE
Allow replace files same name

### ISSUE THREAD

**Issue by kuamatzin** [oneduo/nova-file-manager#238]
Is there any way to upload a file and replace the existing one?

Currently shows this message:

The selected path [file path] already exists.

It would be nice if we can replace the file

**Comment by Rezrazi** [comment]
Hi

we'll take a look a this and perhaps consider it in a future release in the coming week

**Comment by Rezrazi** [comment]
Hi @kuamatzin 
Sorry for taking this long, but this has been merged now, should be available on the next release (v0.10.0)

Cheers
