### ISSUE TITLE
<Code>AccessControlListNotSupported</Code>

### ISSUE THREAD

**Issue by HeadStudios** [oneduo/nova-file-manager#249]
**Describe the bug**
I can upload images but I can't create folders in my s3 bucket

**To Reproduce**
Connect to s3 for a subdirectory disk in s3 e.g file system as:

'blog_images' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'root' => 'images/blog', // <--- This is the new line
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => true,
        ],

**Expected behavior**
Can upload folder

**Screenshots**
Video for context: https://p147.p4.n0.cdn.getcloudapp.com/items/QwuwYK6G/dcd5bc5c-1948-49df-99af-c06064632e51.mp4?v=82d61e6f016e956a7deb0c6ebad0b713
![Image 2023-06-07 at 6 08 53 pm](https://github.com/oneduo/nova-file-manager/assets/4220965/b3d00d61-8f3d-4de7-92ee-a77b8757139b)

AI Conversation about this:
https://chat.openai.com/share/71395f9c-3cc5-4de3-b5b8-524bc2cb6b7d

**Desktop (please complete the following information):**

MacOS
Chrome
Version 114.0.5735.106 

**Smartphone (please complete the following information):**

**Additional context**
Have changed bucket policy for my s3 as follows:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicRead",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectVersion"
            ],
            "Resource": "arn:aws:s3:::rent-roll-devour-bucket-a1/*"
        },
        {
            "Sid": "PublicWrite",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::rent-roll-devour-bucket-a1/*"
        }
    ]
}

**Comment by Rezrazi** [comment]
This is an issue related to your S3 Bucket configuration: "This bucket does not allow ACLs"
