### ISSUE TITLE
Display label for multiple upload 

### ISSUE THREAD

**Issue by davinyoeun** [oneduo/nova-file-manager#252]
<img width="921" alt="Screenshot 2023-06-23 at 9 41 16 AM" src="https://github.com/oneduo/nova-file-manager/assets/129028087/4b81a842-cd4c-4ea0-b2bd-c32bb82f4942">

**Comment by Rezrazi** [comment]
I'm sorry but your issue lacks context and explanation, and seems out of scope of the package
