### ISSUE TITLE
Incompatibility with ```simple-repeatable``` field 

### ISSUE THREAD

**Issue by Algeneralo** [oneduo/nova-file-manager#253]
I'm having an issue with the latest version '0.9.2' with https://github.com/outl1ne/nova-simple-repeatable package.
I guess this may be like #70.

**Comment by Rezrazi** [comment]
Hi, yes you can try to use a wrapper as described here https://oneduo.github.io/nova-file-manager/field.html#third-party-compatibility

As we cannot ensure compatibility for every 3rd party package, we'll however gladly take a look at any PRs that improves this
