### ISSUE TITLE
Uncaught (in promise) Error (stuck on loading screen)

### ISSUE THREAD

**Issue by HeadStudios** [oneduo/nova-file-manager#254]
**Describe the bug**
When opening the File Manager popup it just stays stuck on loading screen:
https://share.getcloudapp.com/mXuG5wnE

No matter what disk I select I get a Uncaught (in promise) Error:
https://p147.p4.n0.cdn.getcloudapp.com/items/04uvNp1J/ff1a7c4b-44ec-4ecc-b28a-addbd79a3b71.jpg?v=ad4ab31d6357dfcfca98ed4c70554e7a

**To Reproduce**

1. Go to Nova resource with file manager
2. Try to open a file

**Expected behavior**
Should be able to see popup of the screen

**Screenshots**

Screenshots:
https://p147.p4.n0.cdn.getcloudapp.com/items/04uvNp1J/ff1a7c4b-44ec-4ecc-b28a-addbd79a3b71.jpg
https://p147.p4.n0.cdn.getcloudapp.com/items/mXuG5wnE/00075bbd-05ad-4cbf-bf74-65da86d744c7.jpg
Video for context: https://share.getcloudapp.com/E0uL4x7O

**Desktop (please complete the following information):**

- OS: MacOS Big Sur
- Browser Chrome
- Version Latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rezrazi** [comment]
Hi

it seems that you are using the new Repeater field, which is still in Beta currently, so you may experience some weird behaviors as we have not had the time to experiment the compatibility.

Meanwhile, you could try to use a wrapper to see if it solves your issue https://oneduo.github.io/nova-file-manager/field.html#third-party-compatibility

We'll gladly take a look at a PR that improves compatibility with non regular fields.

Cheers
