### ISSUE TITLE
You are running an outdated version of the package, a new version is available. even after composer update

### ISSUE THREAD

**Issue by HeadStudios** [oneduo/nova-file-manager#298]
**Describe the bug**
When I go into the File Manager tool it gives me notice at the top:
You are running an outdated version of the package, a new version is available.

However this is still there even after doing composer update. 

I'm not sure how to update - can you give me instructions? Thanks!

**To Reproduce**
Download an older version and then do composer update I guess

**Expected behavior**
Running composer update should remove the error

**Screenshots**

**Desktop (please complete the following information):**

MacOS Big Sur
Chrome
Version 116.0.5845.179 (Official Build) (arm64)

**Smartphone (please complete the following information):**

**Additional context**
Video for context: 
https://rrdevours.monster/storage/support/issue_nova_file-manager.mp4

**Comment by Rezrazi** [comment]
Hi
Could you try to clear your cache?

**Comment by HeadStudios** [comment]
Hi!

Thanks for your quick response - I have done a hard refresh in my Chrome browser as well as php artisan optimize:clear and that error message is not going away on the tool unfortunately :( for the record the tool works great and there's no problems just the upgrade message.

**Comment by Rezrazi** [comment]
As a way to mitigate this, could you set update_checker.enabled to false please?

And the. Could you share your composer.lock and composer.json files please? Please make sure the composer.json doesn't contain any credentials and/or personal information

**Comment by HeadStudios** [comment]
Certainly!

composer.lock
https://gist.github.com/HeadStudios/a6f5072b1fdea828ca66f8c5e016aaa7

composer.json
https://gist.github.com/HeadStudios/06dc4525daf14230c9b8cd06dd8e43ee

I can confirm setting update_checker to false has fixed the issue of not showing that warning.

Any other input much appreciated but otherwise there's no problem here works great :)

**Comment by Rezrazi** [comment]
Yeah something seems to be off with the update checker, we'll investigate this further.

Keeping this open to deliver updates later on

Thanks

**Comment by HeadStudios** [comment]
Thank you - am available to provide more info if required. Thank you again.

**Comment by Rezrazi** [comment]
@HeadStudios you're running an outdated version of the package sitting at v0.8.4
The current latest version is v0.12.0

As composer considers minor versions "major" for 0.x releases, you need to manually specify you want to upgrade the package:
`composer require oneduo/nova-file-manager:^0.12.0`
