### ISSUE TITLE
Nova flexible content - 404 when fetching media in filemanager

### ISSUE THREAD

**Issue by Elvinca** [oneduo/nova-file-manager#313]
Hi there, i think this is probably not anything related to package itself, but rather my own implementation. But still i will try asking like this so other people might find this useful in the future.

I am using nova custom package called [flexible content](https://github.com/whitecube/nova-flexible-content). Now when I try to add new section of content with file manager field, when I open the filemanager, it fetches with this url (and returns 404, stuck in loading screen of manager):

/nova-vendor/nova-file-manager/posts? path=%2F&perPage=15&attribute=**cTpGrGTwwH5oAhft__image**&resource=posts&fieldMode=true&resourceId=56

I intentionally highlighted the url parameter "attribute", because if i try to fetch it with same URL but without the hash (section ID of current file manager field), it returns all needed data.

What would u suggest to do ?

Thx

**Comment by Elvinca** [comment]
Okay, i found out problem happens in this file: BaseRequest.php

![image](https://github.com/oneduo/nova-file-manager/assets/70513191/484da7ee-8449-4ab3-b825-8ddb7440b6ae)

`return $fields
            ->whereInstanceOf(FileManager::class)
            ->findFieldByAttribute($this->attribute, function () {
                abort(404);
            });`
            
Here the $this->attribute is the one with hash, it fails so it returns 404.

**Comment by Rezrazi** [comment]
Have you tried https://oneduo.github.io/nova-file-manager/field.html#third-party-compatibility ?
