### ISSUE TITLE
PHP  `upload_max_filesize` errors do not display error message

### ISSUE THREAD

**Issue by umaraziz0** [oneduo/nova-file-manager#314]
**Describe the bug**
When trying to upload a file with a size above the PHP `upload_max_filesize` configuration, the file manager does not display an error message that the file size is too big, even when file size validation rules are applied.

It seems that the PHP `upload_max_filesize` is validated before Laravel validation rules, hence returning a 520 error instead of a 422 validation error.  

**To Reproduce**

1. Set the `upload_max_filesize` in your `php.ini` to a small number, smaller than the file you want to upload
2. Go to the Nova admin panel
3. Click on the File Manager
4. Upload a file with a larger size than the configured `upload_max_filesize`
5. The page will refresh without displaying any error messages
6. Check the network tab, there will be a request with a 520 error

**Expected behavior**
Should display the "file upload size too big" error message similar to validation messages 

**Screenshots**
![image](https://github.com/oneduo/nova-file-manager/assets/53555790/2fad6fe6-a5a6-4c20-82d3-ff650745608b)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04 LTS
- Browser: Chrome
- Version 118.0.5993.118

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S21 FE
- OS: Android 13
- Browser Chrome
- Version 117.0.5938.156

**Additional context**
n/a

**Comment by Rezrazi** [comment]
There are a few things to consider here:

1. Your server setup seems to be at fault here, as your request is dying before reaching Laravel, and I'm almost certain a basic Laravel upload would fail under the same conditions. (i.e. request will die with a 520 before a 422 from Laravel)
In that case, we recommend checking your Cloudflare/PHP configuration.

2. We understand that the 520 is a fatal error, and the package should intercept it. However, we cannot account for all possible specific status codes that services use, for instance the 520 is specific to Cloudflare (and 499 is nginx-specific as well). We'll gladly accept a PR that attempt to accounts for potential fatal status codes (it's a dependency on resumable.js, chunk size is set at 50MB per chunk)
