### ISSUE TITLE
Download private Files

### ISSUE THREAD

**Issue by JulianMar** [oneduo/nova-file-manager#358]
**Is your feature request related to a problem? Please describe.**
Downloading from a disk which is not made public is not supported

**Describe the solution you'd like**
Downloading a File via an api call which returns the File.

**Comment by Rezrazi** [comment]
Thank you

**Comment by mikaelpopowicz** [comment]
Hi @JulianMar

The issue has been fixed in release [v0.12.2](https://github.com/oneduo/nova-file-manager/releases/tag/v0.12.2)
