### ISSUE TITLE
Not able to upload video.

### ISSUE THREAD

**Issue by philipbaginski** [oneduo/nova-file-manager#367]
Latest version of Nova. Images,  files - no problem to upload. Video - mp4 - error is coming : The file failed to upload.

Mp4 video file is small - 3M, so the size is not w problem.

Every time upload goes to 19%, and error is coming.

Any idea what can be wrong?

**Comment by Rezrazi** [comment]
Are you able to provide some logs of the requests and/or errors that occur within your application?
