### ISSUE TITLE
Installation Issue with oneduo/nova-file-manager on Laravel 11 Project

### ISSUE THREAD

**Issue by FilippoCalabrese** [oneduo/nova-file-manager#369]
**Describe the bug:**
Attempting to install oneduo/nova-file-manager on a Laravel 11 project via Composer leads to a dependency resolution failure. The process indicates that the required pion/laravel-chunk-upload ^1.5 cannot be installed due to a conflict with another requirement.

**To Reproduce:**

1. Run composer require oneduo/nova-file-manager on a Laravel 11 project.
2. Observe the error in the terminal.

**Expected behavior:**
oneduo/nova-file-manager should be installed successfully without any dependency conflicts.

**Screenshots**
![CleanShot 2024-03-18 at 16 46 48@2x](https://github.com/oneduo/nova-file-manager/assets/15164324/c42f0600-e462-4983-95ff-7525c1ec8191)

**Comment by Rezrazi** [comment]
The package is not yet compatible with L11, an update should come by next week

Will gladly accept a PR for this 👍

**Comment by mikaelpopowicz** [comment]
Hi @FilippoCalabrese,

The [pionl/laravel-chunk-upload](https://github.com/pionl/laravel-chunk-upload/releases/tag/v1.5.3) is now compatible with Laravel 11. You're now able to use the file manager with Laravel 11 as well.
