### ISSUE TITLE
Crop Image is not working after update to v0.12.1

### ISSUE THREAD

**Issue by davinyoeun** [oneduo/nova-file-manager#370]
No anchor display for crop image

<img width="1278" alt="image" src="https://github.com/oneduo/nova-file-manager/assets/129028087/40a0c3d5-d803-4c0d-b3b9-019e81707617">

**Comment by mikaelpopowicz** [comment]
Hi @davinyoeun 

Could you please provide more informations ?
- version of Laravel
- version of Nova
- logs from your browser's console

**Comment by davinyoeun** [comment]
I use 
- Laravel 10
- Nova 4
- Chrome browser

**Comment by Rezrazi** [comment]
Are you able to provide some logs from your browser's console?
Just a screenshot is not really helpful to determine the cause of this potential issue

**Comment by Rezrazi** [comment]
@bracketsdigital in your logs, there seems to be an axios request failing with code 500, can you check your network tab / application logs and relay any errors you might find there
