### ISSUE TITLE
Store Activity Log When User Take action on File Manager

### ISSUE THREAD

**Issue by davinyoeun** [oneduo/nova-file-manager#399]
Currently it hard to track who is upload new or old images or files.
I want to record activity of users when they upload replace or delete images or files because

**Comment by Rezrazi** [comment]
Hi @davinyoeun 
The package dispatches some Laravel events on every operation, have you tried building listeners and then implementing your logic?
https://github.com/oneduo/nova-file-manager/tree/main/src/Events

If any events are not working, or some events are missing, please let us know and we'll what we can do
