### ISSUE TITLE
Nova 5 support

### ISSUE THREAD

**Issue by VGirol** [oneduo/nova-file-manager#453]
Hi,

Thanks for your packages. Any chance to get this updated to support Nova 5.x released a few days ago?

Thanks

**Comment by MattLoyeD** [comment]
+1 !

**Comment by mikaelpopowicz** [comment]
Hi @VGirol @MattLoyeD 

The release [v0.13.0](https://github.com/oneduo/nova-file-manager/releases/tag/v0.13.0) adds support to Nova 5.

Cheers.

**Comment by VGirol** [comment]
Thanks !
