### ISSUE TITLE
Missing icons and wrong styling of the FileManager field popup

### ISSUE THREAD

**Issue by Sonicelo** [oneduo/nova-file-manager#89]
When I installed the plugin and wanted to use the FileManager field, I had missing icons and huge graphics on the popup.

![image](https://user-images.githubusercontent.com/10201315/193011631-fbbbb586-0918-407a-b702-166f03c259ac.png)

**To Reproduce**

1. Install fresh version
2. Publish assets
3. Add FileManager field to a resource
4. Navigate to the resource and try to add a file via the field.

**Expected behavior**
Correct graphics/styling

**Solution**
I have already found the solution, but would be great to include this in the documentation for future users. I had to separately run the `php artisan vendor:publish --provider="NovaKit\NovaPackagesTool\LaravelServiceProvider"` command to fix the issue.

**Comment by Rezrazi** [comment]
Hi

I'm unable to reproduce this, having a fresh Nova install and a fresh install of the package at 0.7

Could you please give more details about your issue by providing the different versions you're using
- Laravel Nova
- Nova File Manager

Is this a fresh install of Nova, or an existing Nova application ?

**Comment by Sonicelo** [comment]
Thank you for the fast reply, actually I might have a clue, that something else is wrong here, as it happened again over time, but a refresh solved it. I would close it for now as I am pretty sure its not the packages fault :)
