### ISSUE TITLE
Installation problem.

### ISSUE THREAD

**Issue by philipbaginski** [oneduo/nova-file-manager#90]
Hi,

I have just installed this package following docs. The package was installed with no errors. Registered in Nova Service Provider. Shows in the menu. But does not work, going to url http://127.0.0.1:8000/nova/nova-file-manager gives error: :-( Whoops… Nova experienced an unrecoverable error. 

, or:

cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.github.com/repos/oneduo/nova-file-manager/releases/latest

Any idea what I did wrong?

**Comment by Rezrazi** [comment]
Hi

Please provide more information or details about your issue, as it is not clear what is happening.

- Laravel version
- Laravel Nova version
- PHP version
- Nova File Manager version

Can you check your browser's console or network tab for any relative error messages ?
