### ISSUE TITLE
How to show downloadable url for asset file and preview the file in index page? 

### ISSUE THREAD

**Issue by abrahamarslan** [oneduo/nova-file-manager#91]
![image](https://user-images.githubusercontent.com/14885767/195477924-4c085ebc-13b0-4904-88ea-d6ca364b3547.png)

**Comment by Rezrazi** [comment]
Hi @abrahamarslan 

Thank you for your idea, unfortunately we do not currently have a dedicated view or method for this specifically.
However, we have added the ability to implement a custom `displayUsing()` which, coupled with `asHtml()` may allow you to implement a download link for your asset.

You can use these two methods to implement your own logic and display your value accordingly.

It can look something like this : 
```php
            FileManager::make('avatar')
                ->displayUsing(function ($value) {
                    $avatar = $value[0]; // here value is an array

                    return '<a href="'.$avatar['url'].'" download>'.$avatar['path'].'</a>';
                })
                ->asHtml(),
```

All the best
Charaf
