### ISSUE TITLE
Integrate file manager into ckeditor

### ISSUE THREAD

**Issue by tovantiep** [oneduo/nova-file-manager#92]
I want to integrate file manager into ckeditor 4 , do you have any suggestions?

**Comment by Rezrazi** [comment]
Hi !

Thank you for your idea, but we are currently unable to provide any helpful suggestion regarding this. 

There are many aspects to this, as we do not know which editor/package you are using, and this is something that is going to relate to this same package you are using. The maintainer of said package will have to provide an integration for Nova File Manager, we will gladly help and/or provide any useful information and details to get it to work, please give us a shout !

We are planning on working on our own editor package, which will be based on TipTap and will integrate seamlessly with Nova File Manager, however we do not have an ETA or a timetable for now.

Please do make sure to follow our public channels (Twitter, Github ...) to be notified when this package is made available !

All the best !
Charaf

**Comment by tovantiep** [comment]
Hope what you are developing will be supported by many people, thanks
