### ISSUE TITLE
Support File Visibility

### ISSUE THREAD

**Issue by dylanjeffries** [oneduo/nova-file-manager#97]
The S3 filesystem I'm working with handles assets that should be publicly accessible and then files that should be kept private. 

Being able to set file visibility when uploading and then determine whether the url should be signed based off of that would avoid the needless activity of signing public assets.

Another potential way of avoiding this could be to define in the config which disks should have signed urls, allowing the splitting of public and private assets onto separate disks.

**Comment by Rezrazi** [comment]
Hi,

Thank you for your feedback, and yes the current handler applies signing policies globally in the file manager.
We will be looking to implement this in the coming weeks.

Thanks

**Comment by mikaelpopowicz** [comment]
Hi @dylanjeffries 

You may configure visibility on your disks in the `filesystems.php` configuration file. The configured visibility applies to the whole disk. As we do not store any information about files in database (for the time being), we are unable to figure out if a file should be public or private.

In addition, you may use the `resolveUrlUsing` method to determine how the asset's url is built.

For now we do not plan to add the ability to configure the upload visibility.

```php
// app/Nova/User.php

use Oneduo\NovaFileManager\FileManager;

class User extends Resource
{
    // ...

    public function fields(NovaRequest $request): array
    {
        return [
            // ... any other fields
            FileManager::make(__('Pictures'), 'pictures')
                ->resolveUrlUsing(function (NovaRequest $request, string $path, string $disk, Filesystem $filesystem) {
                    if ($disk === 's3') {
                        return $filesystem->temporaryUrl($path, now()->addMinutes(5));
                    }

                    return $filesystem->url($path);
                })
                ->limit(3),
        ];
    }
}
```

Regards
